StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62CED5495A8054BC}" {
   Id "PS-AmmoType_Matador_HEAT"
   Target_en_us "HEAT"
   Target_en_us_edited ""
   Target_fr_fr "HEAT"
   Target_it_it "HEAT"
   Target_de_de "HEAT"
   Target_es_es "HEAT"
   Target_cs_cz "HEAT"
   Target_pl_pl "HEAT"
   Target_ru_ru "КУМ"
   Target_ja_jp "HEAT"
   Target_ko_kr "HEAT"
   Target_pt_br "HEAT"
   Target_zh_cn "HEAT"
   Target_uk_ua "КУМ"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED549668339C7}" {
   Id "PS-AmmoType_Matador_HESH"
   Target_en_us "HESH"
   Target_en_us_edited ""
   Target_fr_fr "HESH"
   Target_it_it "HESH"
   Target_de_de "HESH"
   Target_es_es "HESH"
   Target_cs_cz "HESH"
   Target_pl_pl "HESH"
   Target_ru_ru "ОФС"
   Target_ja_jp "HESH"
   Target_ko_kr "HESH"
   Target_pt_br "HESH"
   Target_zh_cn "HESH"
   Target_uk_ua "ОФС"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED5495F72D389}" {
   Id "PS-AmmunitionType_HEAT"
   Target_en_us "Anti-Structure"
   Target_en_us_edited ""
   Target_fr_fr "Explosif brisant antichar"
   Target_it_it "Munizione esplosiva anticarro"
   Target_de_de "Hohlladungsgeschoss"
   Target_es_es "Munición anticarro de alto explosivo"
   Target_cs_cz "Protitanková kumulativní munice"
   Target_pl_pl "Amunicja kumulacyjna"
   Target_ru_ru "Кумулятивный снаряд"
   Target_ja_jp "成形炸薬弾"
   Target_ko_kr "성형작약탄"
   Target_pt_br "Munição explosiva antitanque"
   Target_zh_cn "高爆反坦克弹"
   Target_uk_ua "Кумулятивний заряд"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657737954
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED549526016A0}" {
   Id "PS-AmmunitionType_HESH"
   Target_en_us "Squash Head"
   Target_en_us_edited ""
   Target_fr_fr "Explosif plastique brisant"
   Target_it_it "Testa di carica a schiacciamento"
   Target_de_de "Hohlladungsgeschoss"
   Target_es_es "Munición de cabeza aplastante"
   Target_cs_cz "Střela s plastickou hlavicí"
   Target_pl_pl "Głowica zgniatana"
   Target_ru_ru "Боеприпас с пластиковой головкой"
   Target_ja_jp "粘着榴弾"
   Target_ko_kr "압착탄"
   Target_pt_br "Cabeça de carga de esmagamento"
   Target_zh_cn "塑性炸药弹头"
   Target_uk_ua "Боєприпас із пластичною головкою"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657737946
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED5497D5AB017}" {
   Id "PS-Weapon_Matador_HEAT_Description"
   Target_en_us "90mm Man-portable, Anti-Tank, Anti-DOor Anti-Structure Munition High-Explosive Anti-Tank"
   Target_en_us_edited ""
   Target_fr_fr "90mm portable, antichar, anti-porte, munition anti-structure explosif brisant antichar"
   Target_it_it "Portatile da 90 mm, anticarro, antiporta, munizione anti-struttura ad alto esplosivo"
   Target_de_de "90-mm tragbare Panzerabwehr, Anti-Struktur Munition Hoch-Explosiv"
   Target_es_es "90 mm portátil, antitanque, antipuerta, munición anti-estructura de alto explosivo"
   Target_cs_cz "Přenosný 90mm, protitankový, proti dveřím, munice proti struktuře, vysoce explozivní"
   Target_pl_pl "90 mm przenośny, przeciwpancerny, anty-drzwi, amunicja przeciwstrukturalna, wysokowybuchowa"
   Target_ru_ru "Переносной 90 мм, противотанковый, противодверной, противоструктурный боеприпас высокоэксплозивный"
   Target_ja_jp "90mm 携帯型、対戦車、対ドア、対構造用高性能対戦車弾"
   Target_ko_kr "90mm 휴대용 대전차, 대문, 구조물 방어 고성능 대전차탄"
   Target_pt_br "90 mm portátil, antitanque, antiporta, munição anti-estrutura de alto explosivo"
   Target_zh_cn "90毫米便携式，反坦克，防门，反结构高爆反坦克弹"
   Target_uk_ua "Портативний 90 мм, протитанковий, протидверний, протиструктурний боєприпас високої вибухової потужності"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED54911C0D614}" {
   Id "PS-Weapon_Matador_HEAT_Name"
   Target_en_us "L2A1 MATADOR ASM HEAT"
   Target_en_us_edited ""
   Target_fr_fr "L2A1 MATADOR ASM HEAT"
   Target_it_it "L2A1 MATADOR ASM HEAT"
   Target_de_de "L2A1 MATADOR ASM HEAT"
   Target_es_es "L2A1 MATADOR ASM HEAT"
   Target_cs_cz "L2A1 MATADOR ASM HEAT"
   Target_pl_pl "L2A1 MATADOR ASM HEAT"
   Target_ru_ru "L2A1 MATADOR ASM HEAT"
   Target_ja_jp "L2A1 MATADOR ASM HEAT"
   Target_ko_kr "L2A1 MATADOR ASM HEAT"
   Target_pt_br "L2A1 MATADOR ASM HEAT"
   Target_zh_cn "L2A1 MATADOR ASM HEAT"
   Target_uk_ua "L2A1 MATADOR ASM HEAT"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED54906D187BA}" {
   Id "PS-Weapon_Matador_HESH_Description"
   Target_en_us "90mm Man-portable, Anti-Tank, Anti-DOor Anti-Structure Munition High-Explosive Squash Head"
   Target_en_us_edited ""
   Target_fr_fr "90mm portable, antichar, anti-porte, munition anti-structure plastique brisant"
   Target_it_it "Portatile da 90 mm, anticarro, antiporta, munizione anti-struttura testa schiacciata"
   Target_de_de "90-mm tragbare Panzerabwehr, Anti-Struktur Munition Hoch-Explosiv-Zerquetschkopf"
   Target_es_es "90 mm portátil, antitanque, antipuerta, munición anti-estructura de cabeza aplastada"
   Target_cs_cz "Přenosný 90mm, protitankový, proti dveřím, munice proti struktuře, squashová hlava"
   Target_pl_pl "90 mm przenośny, przeciwpancerny, anty-drzwi, amunicja przeciwstrukturalna, spłaszczona głowica"
   Target_ru_ru "Переносной 90 мм, противотанковый, противодверной, противоструктурный боеприпас с расплющенной головкой"
   Target_ja_jp "90mm 携帯型、対戦車、対ドア、対構造用高性能弾頭"
   Target_ko_kr "90mm 휴대용 대전차, 대문, 구조물 방어 고성능 스쿼시 헤드"
   Target_pt_br "90 mm portátil, antitanque, antiporta, munição anti-estrutura de cabeça achatada"
   Target_zh_cn "90毫米便携式，反坦克，防门，反结构高爆弹头"
   Target_uk_ua "Портативний 90 мм, протитанковий, протидверний, протиструктурний боєприпас з розплющеною головкою"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CED549186B47D7}" {
   Id "PS-Weapon_Matador_HESH_Name"
   Target_en_us "L2A1 MATADOR ASM HESH"
   Target_en_us_edited ""
   Target_fr_fr "L2A1 MATADOR ASM HESH"
   Target_it_it "L2A1 MATADOR ASM HESH"
   Target_de_de "L2A1 MATADOR ASM HESH"
   Target_es_es "L2A1 MATADOR ASM HESH"
   Target_cs_cz "L2A1 MATADOR ASM HESH"
   Target_pl_pl "L2A1 MATADOR ASM HESH"
   Target_ru_ru "L2A1 MATADOR ASM HESH"
   Target_ja_jp "L2A1 MATADOR ASM HESH"
   Target_ko_kr "L2A1 MATADOR ASM HESH"
   Target_pt_br "L2A1 MATADOR ASM HESH"
   Target_zh_cn "L2A1 MATADOR ASM HESH"
   Target_uk_ua "L2A1 MATADOR ASM HESH"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657735778
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
 }
}